const LIST = {
	Name: require("./Name").default,
	Constant: require("./Constant").default,
	ClassDef: require("./ClassDef").default,
	Body: require("./Body").default,
	Tuple: require("./structs/Tuple").default,
	List: require("./structs/List").default,
	Dict: require("./structs/Dict").default,
	UnaryOp: require("./operators/UnaryOp").default,
	Subscript: require("./operators/Subscript").default,
	Compare: require("./operators/Compare").default,
	BoolOp: require("./operators/BoolOp").default,
	BinOp: require("./operators/BinOp").default,
	AugAssign: require("./operators/AugAssign").default,
	Attribute: require("./operators/Attribute").default,
	Assign: require("./operators/Assign").default,
	Return: require("./keywords/Return").default,
	Raise: require("./keywords/Raise").default,
	Pass: require("./keywords/Pass").default,
	Continue: require("./keywords/Continue").default,
	Break: require("./keywords/Break").default,
	Assert: require("./keywords/Assert").default,
	alias: require("./import/alias").default,
	ImportFrom: require("./import/ImportFrom").default,
	Import: require("./import/Import").default,
	keyword: require("./functions/keyword").default,
	FunctionDef: require("./functions/FunctionDef").default,
	Call: require("./functions/Call").default,
	Args: require("./functions/Args").default,
	JoinedStr: require("./fstring/JoinedStr").default,
	FormattedValue: require("./fstring/FormattedValue").default,
	While: require("./controlflows/While").default,
	Try: require("./controlflows/Try").default,
	IfExp: require("./controlflows/IfExp").default,
	If: require("./controlflows/If").default,
	For: require("./controlflows/For").default,
	ExceptHandler: require("./controlflows/ExceptHandler").default,
}

import ILIST from './index';
Object.assign(ILIST, LIST);
export default ILIST;
